
const SEVERITY_TYPE = {
	INFO: "info",
	SUCCESS: "success",
	WARN: "warn",
	ERROR: "error",
};
const KEY_SESSION_STORAGE = {
	KEY_TOKEN: "KEY_TOKEN",
	KEY_USER: "KEY_USER",
	KEY_LANGUAGE: "KEY_LANGUAGE",
	KEY_APPMAPPING: "KEY_APPMAPPING"
};
export {
	SEVERITY_TYPE,
	KEY_SESSION_STORAGE
}